All ow hiding complications on when watch is locked
home-assistant/iOS pull request #1253
Opened 2020-10-29 18:00 UTC by TomBrien

Given that we essentially let users add anything from Home Assistant that can be represented as text as a complication I thought it would be a good idea to let people choose whether or not to display a complication when the watch is locked.

Tested on my watch and seems to be working 😯although I haven't tested the Realm migration yet. Apologies in advance, this is my first time trying something of this complexity (for me, appreciate it's actually pretty simple)

2020-10-29 20:13 UTC, TomBrien commented
Hmm I'm getting:
> Database Error
> Migration is required due to the following errors:
> - Property 'WatchComplication.IsPrivate' hass been added.

Pop up. Not sure what I did differently to https://github.com/home-assistant/iOS/blob/master/Sources/Shared/Common/Extensions/Realm%2BInitialization.swift#L89-93

2020-10-29 20:59 UTC, TomBrien commented
Migration should be resolved now

2020-10-31 05:09 UTC, zacwest requested changes
overall nice job! just a couple suggestions.

2020-10-31 05:09 UTC, zacwest commented on Sources/App/Settings/AppleWatch/ComplicationEditViewController.swift
> +            $0.value = self.config.IsPrivate
I think it is worth flipping the way this is presented. "Show When Locked <default on>" is a little easier to mentally discern than the double-negative "Hide when locked <default off>".

2020-10-31 05:09 UTC, zacwest commented on Sources/Extensions/Watch/ComplicationController.swift
> +        if #available(watchOS 7, *), complication.identifier != CLKDefaultComplicationIdentifier {
given this is from another method in this class, i think it's worth writing a helper function like `func complication(for complication: WatchComplication) -> WatchComplication?`

2020-11-01 21:05 UTC, TomBrien commented
Had a bit of issues getting complications to sync. Should note I've seen this since the restructuring of complications for watchOS 7. I think it may be a me thing but interested if can be reproduced by others. Complication privacy is still working and tested though. Bottom complications are both HA left is set with Show on When Locked true right has it false. 
Unlocked![image](https://user-images.githubusercontent.com/12411302/97815432-daae0d80-1c85-11eb-8934-605aab8dc146.png)
Locked ![image](https://user-images.githubusercontent.com/12411302/97815430-d255d280-1c85-11eb-8c60-2d5dc6f57c99.png)

2020-11-02 01:16 UTC, zacwest approved these changes
just minor - let's try and keep to swift-isms for function names here

2020-11-02 01:16 UTC, zacwest commented on Sources/Extensions/Watch/ComplicationController.swift
> +    private func getComplicationModel(for complication: CLKComplication) -> WatchComplication? {
prefixing functions with 'get' is not really a swift-ism that works super well -- apple's been leaning on doing this only for asynchronous returns (e.g. it provides a block)

2020-11-02 01:16 UTC, zacwest commented on Sources/Extensions/Watch/ComplicationController.swift
> +        model = getComplicationModel(for: complication)
if you pull this up into the variable declaration above you can avoid needing to declare the type, too

2020-11-02 17:21 UTC, merged