Add Firefox Focus/Klar as browsers for opening links
home-assistant/iOS pull request #2213
Opened 2022-10-01 01:50 UTC by davidjb

## Summary

This adds support to open URLs in Firefox Focus/Klar. Firefox Focus and Klar are the same project
(see https://github.com/mozilla-mobile/focus-ios; and https://support.mozilla.org/en-US/kb/difference-between-firefox-focus-and-firefox-klar), but use different app scheme prefixes on account of the FOCUS name being used by a Mozilla partner in Germany, Austria and Switzerland.

This PR adapts and reuses the existing Firefox URL opener to being able to accept a different scheme for each app, defaulting to the standard `firefox://` prefix for regular Firefox.

## Screenshots

## Link to pull request in Documentation repository

Documentation: home-assistant/companion.home-assistant#

## Any other notes

From reading the developer docs, I'm unclear on if/how I should update the `Localizable.strings` files for other languages at this point. If there's something else I need to do for this PR, just let me know 👍 

Also, I've done my best with fastline linting/autocorrect but my local setup is having some issue with finding CFPropertyList-3.0.5 and it crashing out at the end. So, it looks okay but again let me know - or CI/GitHub Actions will I'm sure.

2022-10-01 13:43 UTC, davidjb commented
So fwiw, the issue I was having running any `fastlane` commands was that Ruby commands were erroring out with:

    Could not find CFPropertyList-3.0.5 in any of the sources

and equivalent messages. To solve/workaround the issue, I ran:

    $(brew --prefix)/opt/ruby@3.1/bin/bundle exec fastlane install_plugins

The two `fastlane` plugins it updated seem unrelated, so I can't say precisely why this works, but it did run a step installing plugin dependencies – so I'm guessing that somehow ensured `CFPropertyList` was installed correctly.

2022-10-03 17:35 UTC, zacwest requested changes
other languages' localization files are updated automatically (it goes english -> lokalize -> back down to other languages) so you have done the right thing here. just this enum comment and otherwise looks good!

2022-10-03 17:35 UTC, zacwest commented on Sources/App/Utilities/OpenInFirefoxControllerSwift.swift
> +    var urlScheme: String
this should probably be an enum, e.g.:

```swift
enum FirefoxType {
  case regular
  case focus
  case klar

  var urlScheme: String {
    switch self { /* … */ }
  }
}
```

2022-10-04 00:52 UTC, davidjb commented
Thanks for the code review @zacwest & insight on localisation. I've added an `enum` as per your suggestion - it's cleaned things up nicely. Tested the adjusted code with Firefox Focus and standard Firefox in the simulator and works well. Let me know if any other changes are needed.

2022-10-07 17:19 UTC, zacwest approved these changes
thanks!

2022-10-07 17:20 UTC, merged