Move test classes to test main folder;
home-assistant/iOS pull request #2807
Opened 2024-06-03 17:51 UTC by mat1th

## Summary
This pr does move test files to the test folder of the project.

## Screenshots
NA

## Link to pull request in Documentation repository
-

## Any other notes
-

2024-06-04 09:29 UTC, bgoncal requested changes
Minor comments, but looking good! Thanks for helping out

2024-06-04 09:29 UTC, bgoncal commented on Sources/App/Scenes/SettingsSceneDelegate.swift
> -    @objc private func selectItem(_ item: NSToolbarItem) {
Did the linter update this?

2024-06-04 09:29 UTC, bgoncal commented on Sources/App/Utilities/UIImage+scaledToSize.swift
> +extension UIImage {
Can you make a folder for extensions? I saw we have  a few inside Utilities

2024-06-06 16:35 UTC, mat1th commented on Sources/App/Scenes/SettingsSceneDelegate.swift
> -    @objc private func selectItem(_ item: NSToolbarItem) {
Yes, can revert it.

2024-06-07 09:06 UTC, bgoncal approved these changes

2024-06-07 09:06 UTC, merged