Remove some depricated code pointed in #2655;
home-assistant/iOS pull request #2808
Opened 2024-06-03 18:15 UTC by mat1th

## Summary
In issue #2655 there is some code referenced that is not needed anymore. So I've removed it.

## Screenshots
The app still launches on a iPhone simulator. Could not test the macOS target.

## Link to pull request in Documentation repository
Documentation: home-assistant/companion.home-assistant#

## Any other notes
-

2024-06-04 08:13 UTC, mat1th commented on Sources/App/Notifications/NotificationManager.swift
> -        var methods: UNNotificationPresentationOptions = [.alert, .badge, .sound]
alert is deprecated since iOS 14 see https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/alert

2024-06-04 08:13 UTC, mat1th commented on Sources/App/WebView/IncomingURLHandler.swift
> +                case .rejected:
Error value was not used;

2024-06-04 09:25 UTC, bgoncal commented
Thank you!
For the linter:
`bundle exec fastlane autocorrect`

2024-06-04 09:31 UTC, bgoncal commented on Sources/App/WebView/IncomingURLHandler.swift
> +                case .rejected:
Perhaps this instead:
`                    Current.Log.error("Failed to obtain webview to open Assist In App: \(error.localizedDescription)")
`

2024-06-07 10:11 UTC, bgoncal approved these changes
Looks good to me, I'll run some manual tests just to be sure

2024-06-07 14:56 UTC, bgoncal commented on Sources/App/Notifications/NotificationManager.swift
> -        var methods: UNNotificationPresentationOptions = [.alert, .badge, .sound]
Perhaps we should follow the deprecation message?

`Deprecated
Use [list](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/list) and [banner](https://developer.apple.com/documentation/usernotifications/unnotificationpresentationoptions/banner) instead.`

2024-06-07 14:57 UTC, bgoncal commented on Sources/App/Notifications/NotificationManager.swift
> -                methods.insert(.alert)
Same here

2024-06-07 14:59 UTC, bgoncal requested changes
Tested and all looks good, just this suggestion above , ler me know what you think

2024-06-08 06:38 UTC, mat1th commented on Sources/App/Notifications/NotificationManager.swift
> -        var methods: UNNotificationPresentationOptions = [.alert, .badge, .sound]
Good point, I've added them.

2024-06-10 08:03 UTC, bgoncal approved these changes

2024-06-10 08:03 UTC, merged

2024-06-10 08:03 UTC, bgoncal commented
Thank you!