Redesign Sensor widget
home-assistant/iOS pull request #3172
Opened 2024-11-18 16:31 UTC by Penait1

## Summary
Redesign of the Sensor widget, this is a WIP mr to collect early feedback. The new view is not implemented yet

## Screenshots
Comes later

2024-11-19 18:59 UTC, Penait1 commented
@bgoncal I think its ready for review, the test step seems to be failing but I'm not sure why

2024-11-20 10:06 UTC, bgoncal commented on Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
> +                                    WidgetBasicButtonView(model: model, sizeStyle: sizeStyle, tinted: false)
Should this case always be a button view?

2024-11-20 10:25 UTC, bgoncal requested changes
Just tested on my device and it looks great! One minor thing, the widget background needs to be that gray-ish that the other widgets before, because we try tor eplicate the lovelace UI, gray-ish bg + white background tile, I think the design I shared with you had the wrong bg as well, my bad.

Also are you planning to add more sizes? (can be in a separate PR of course)

2024-11-20 16:05 UTC, Penait1 commented on Sources/Extensions/Widgets/Common/WidgetBasicContainerView.swift
> +                                    WidgetBasicButtonView(model: model, sizeStyle: sizeStyle, tinted: false)
Mm no I was mistaken

2024-11-20 16:08 UTC, Penait1 commented
Yes I'm planning more sizes but I'll do it in a separate pr. 

I quickly checked if the sensor type view works with bigger sizes and it works. I'll have to do some extra stuff for the snapshot preview still I think

2024-11-20 17:15 UTC, bgoncal approved these changes

2024-11-20 17:15 UTC, merged